### PR TITLE
Integrate npc_battle struct with battle code

### PR DESCRIPTION
**Pull request by lczielinski**
In this pull request, we replaced the old npc_enemy_t struct with the new struct implemented by the npc team, npc_battle_t. This new struct is part of the more general npc_t struct. We modified functions especially in battle_flow, since many functions involved taking in an npc_enemy_t and turning it into a combatant_t. One difference with an npc_t and npc_enemy_t is that npc_t (and npc_battle_t) requires moves, stats, and descriptions to not be null. This caused some changes in the way enemies were created and their moves created with build_moves() (the move had to be created with the enemy, rather than the enemy being created then the move being added). Furthermore, the npc_t struct does not contain next and prev fields like the old npc_enemy_t struct did, so for now, multiple enemies in a single battle is not implemented. We updated all tests and examples, which function just as before.

### CODE REVIEW

**Comment by firatciftci** [comment]
@lczielinski It seems the automated tests for this PR's branch is currently failing due to other PRs being merged to `dev`. You should check out the CI log and try to fix the issue before the reviewers can submit their reviews. Let me know if you have any questions/issues with this.

**Comment by lczielinski** [comment]
The issue was with linking the npc and game-state libraries. The fix was to add the line "target_link_libraries(game-state npc)" to the game-state CMake file.

**Review by adinilfeld — APPROVED** [review]
Looks great!

**Review by sonnykaiyuenlee — APPROVED** [review]
looks like you guys changed a lot, good work!

**Review by firatciftci — APPROVED** [review]
Everything looks good to me, great work!

**Comment by lczielinski** [comment]
To summarize this pull request, the NPC team integrated our npc_enemy_t struct into their main npc_t struct. We refactored functions, especially in battle_flow.c, tests, and examples to use this new struct, and removed the old struct from our code. The npc_battle_t struct (the new struct within npc_t) cannot be created with null stats and moves, and the npc_t cannot be created with null descriptions. In the future, we will add more functionality for the npc_t struct to hold battle_item_t that enemies can use in battle.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this!

**Pull request merged**
