### PR TITLE
Cli/testing parse r

### PR DESCRIPTION
**Pull request by Beza20**
With this pull request, I have included multiple tests for the function that is instrumental in resolving #275 which is parse_r whose details one can find on the issue documentation. The tests check if a cmd_line is parsed through and put into a list by comparing it to an array of strings containing those cmds in the same order. Details for the helper function used to test can be found on the documentation for issue #1119

### CODE REVIEW

**Review by ecoble — APPROVED** [review]
Nice job! These tests have great coverage!

**Review by dchen0258 — APPROVED** [review]
LGTM! Nice work!

**Comment by Beza20** [comment]
Chiventure's testing module now supports an expansive test for the function parse_r that was merged with the pull request #1048. details of what the test incorporates is in the issue #1119.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
These tests are excellent, great work!

**Pull request merged**
