### PR TITLE
Prevent chiventure from starting in terminals smaller than 80 columns x 24 rows

### PR DESCRIPTION
**Pull request by jackandthebean**
In the `ui/terminal-dimensions` branch, chiventure now refuses to run if the terminal doesn't have the required size. The minimum dimensions are easily reconfigured, as macros `MIN_COLS` and `MIN_ROWS` are now defined in `ui.h`.

ade11ece8c25d4e85ca308742966e1cc833a23c2

I consulted [this](https://psychocod3r.wordpress.com/2019/02/25/how-to-get-the-dimensions-of-a-linux-terminal-window-in-c/) tutorial to obtain the dimensions of the terminal.

### CODE REVIEW

**Comment by jackandthebean** [comment]
Thank you @VannStrasen @firatciftci !! So, what happens now that the PR has gotten the two necessary approvals? Should I close this PR?

**Comment by firatciftci** [comment]
The pull request has been successfully merged to `dev`! 🎉

**Comment by jackandthebean** [comment]
The branch I created to make chiventure refuse to run if the terminal doesn't have the required dimensions has now been merged into `dev`, so I am closing this issue! However, it seems like a good idea to also implement a way to put chiventure on hold if after starting successfully in a terminal of the correct dimensions, a user resizes their terminal to unsupported dimensions. I added an issue describing this enhancement to the backlog – #650. If I have time I may also take on this issue in Sprint 4; otherwise, anyone can claim this enhancement!

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The only thing I'll point out is that the summary should have been a bit more detailed; ideally, it is a paragraph long and outlines the purpose and the exact changes of the PR.

**Pull request merged**
