### PR TITLE
Integrated NPCs with rooms

### PR DESCRIPTION
**Pull request by jeyeong**
Added NPCs to rooms by making the following changes:

- Added an `npcs` field to the room struct.
- Resolved circular dependency issues, by adding forward declarations.
- Modified room_new() and room_free() to create / free the `npcs` field.

### CODE REVIEW

**Review by mbutera17 — APPROVED** [review]
Changes shouldn't have any negative impacts on our team. Looks good!

**Review by lilyehsani — APPROVED** [review]
All looks good!

**Comment by jeyeong** [comment]
Summary of changes:
- Integrated NPCs with rooms by adding an `npcs` field (which is a npcs_in_room struct) to the game struct.
- Introduced a function, `get_npc_in_room()`, that lets us retrieve NPCs from rooms (or check if they are in one).

Next steps:
- Complete the implementation of the <talk to> function.
- Write our game demo.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! Make sure to assign new PRs to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")

**Pull request merged**
