### PR TITLE
Openworld: Introduce levelspec_t struct (with associated tests and helpers)

### PR DESCRIPTION
**Pull request by Justin08784**
**_Created_ a new `levelspec_t` struct which neatly packages all the info needed for level-oriented generation. This will make refactoring/expanding level-oriented generation functionality much simpler as we only need to edit or add/delete the fields of `levelspec_t`. `levelspec_t` helpers (init, new, and free) were implemented along with relevant tests in gen_structs.c. 

`difficulty_level_scale_t` (with associated helpers and tests) was removed. We now have `int *thresholds` and `int num_thresholds` fields in `levelspec_t` which serve the same purpose. 

**_Renamed_ `room_level_t` to `roomlevel_t`. Functions involving `roomlevel_t` were renamed appropriately.

Other changes:
- Discovered and fixed a bug in filter_speclist_with_difficulty() (details [here](https://github.com/uchicago-cs/chiventure/issues/1034#issuecomment-844497100)).
- Simplified multi_room_level_generate() tests. Similar changes should be made to multi_room_generate() tests in a followup task.

### CODE REVIEW

**Review by ahmed-sumaiya — APPROVED** [review]

**Review by ahmed-sumaiya — APPROVED** [review]
I reviewed the files and it looks good to me

**Review by wmingyan — COMMENTED** [review]
It might be better to let each hashable struct have a structname_hash_t variant defined to differentiate between structname_t pointers which are used to point to the structs in the traditional sense, and those which are used to hash the structs with the UTHASH macros. For example, in item.h, `typedef struct item {...} item_t;` vs. `typedef struct item item_hash_t;`. If so, all the functions/tests should be updated to reflect this.

**Review by wmingyan — APPROVED** [review]
Looks great to me!

**Review by MaxineK36 — APPROVED** [review]
LGTM!

**Comment by Justin08784** [comment]
Closing statement:
Comments by reviewers have been addressed and branch `openworld/add-levelspec` is now merged into dev. recursive_generate is now available across all other modules.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! For next time, it would also be helpful to put a very short summary of the changes made in your closing statement.

**Pull request merged**
