### PR TITLE
Added new .wdz test game & script to easily author such games

### PR DESCRIPTION
**Pull request by namanhd1nh**
As part of the WDL++ spec, I've written a test game in the new format to demonstrate some of the core functionality such as actions, items, rooms, and conditionals. Specifically, actions make full use of the custom actions interface, with action sequences taking parameters. RPG features are not present as they are very much works in progress.

My notes and documentation about this test game, including suggested WDL++ spec changes as I went along with writing the game, are available in the `README_test_game.md` file.

As part of the process of producing test games, I've also written a command line utility `wdz` (just a shell script) to automate the process of creating the correct game folder structure and corresponding .wdz zip archive, as well as updating the archive with changes to the game folder. This is to streamline the process of authoring .wdz games (at least, as far as manually editing the JSON files goes.) Documentation for this is available in the `README_wdz.md` file.

Addresses issue #536.

### CODE REVIEW

**Comment by namanhd1nh** [comment]
> certain of inconsistencies in indentation/syntax within this code

In fact I think this is one of the best benefits of switching over to JSON, which is that its syntax doesn't rely on whitespace and indentation at all, as everything is properly demarcated with braces and brackets, so we don't actually have to worry about this at all! 
This also means I was able to do stuff like "fake-indenting" the "if" blocks in the action sequences to make it look more like "code blocks" with hierarchies, as you have probably also seen.

**Comment by namanhd1nh** [comment]
I pushed a new commit that fixes the "push" actions of the levers to actually have the correct "push" call. Before, they were erroneously left as "pull", the same call as the "pull" actions, due to copy-paste errors.

**Comment by namanhd1nh** [comment]
The wdz script and a sample test game .wdz archive and folder has been merged into dev, inside src/wdl/sandbox for now. The sample game will serve as a reference game for present and future WDL developers to test out zip opening and JSON parsing; and the shell script can act as a "game compiling" tool to help developers and authors alike prototype new games quickly before a dedicated WDL game creation program is conceived.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Awesome work! The closing statement makes it very easy to understand what was accomplished in this PR.

**Pull request merged**
