### PR TITLE
Implemented add-move function that will help with integration with skilltree

### PR DESCRIPTION
**Pull request by Elsa-Athiley**
@tgao564 reached out to us about integrating skills with battles.The overall idea is to allow players to gain moves when certain skills are unlocked. We determined that  creating a function that adds a move to a player's linked list of moves as a part of our code would be helpful. More information can be found in the issue #979. In this code we've implemented the add-move function as well as moved battle_move_maker out of the examples directory

### CODE REVIEW

**Review by jintae412 — APPROVED** [review]
The code seems solid, and easy to build upon in the future in case we decide to for instance change how moves are structured. Very nice job!

**Review by firatciftci — APPROVED** [review]
Looks good!

**Comment by Elsa-Athiley** [comment]
Closing comment: In this PR we added an add-move function that will help with implementation of skill based moves. This function adds a move to a player's existing linked list of moves. We also moved battle_move_maker file out of the examples directory into the src directory.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job!

**Pull request merged**
