### PR TITLE
Merge attempt #2 -- Moved coordinant main fcn into a seperate example directory

### PR DESCRIPTION
**Pull request by omorkved**

### CODE REVIEW

**Comment by omorkved** [comment]
@mpcsh Hello! How should I go about addressing the failed check for continuous integration? I'm a bit unsure since it relates to the Travis CI

**Comment by borjasotomayor** [comment]
@omorkved: Not sure why GitHub is running a build for this pull request, since it's to dev and not to master. I looked at the build, and it's trying to build the code for PR #85 (the one you closed). Not sure how GitHub ended up in that situation, but I think you can just ignore it.

**Comment by borjasotomayor** [comment]
Side note: Does this PR really require three reviews? Code reviews to dev typically only require one (or, at most, two) reviews. Three reviews is overkill for a non-master PR this small.

**Comment by omorkved** [comment]
> Side note: Does this PR really require three reviews? Code reviews to dev typically only require one (or, at most, two) reviews. Three reviews is overkill for a non-master PR this small.

ahh whoops that's our bad. we thought every pull request required three reviews in the guidelines but I'm realizing now we must have misread.

**Pull request merged**
