### PR TITLE
Graphics Inventory #1 Pull Request

### PR DESCRIPTION
**Pull request by imadejski**
Inventory graphics module created with inventory_graphics.h  inventory_graphics.c. New init free functions created for the structs. This is a crucial part of the inventory module, as we need to initialize and free the slot structs that we have created such that they will be able to be used in the display of our inventory.

### CODE REVIEW

**Review by dhirpalshah — APPROVED** [review]
Looks good to me!

**Review by philipchenaux — CHANGES_REQUESTED** [review]
I noticed the you added a Makefile even though it is empty, what is the reasons for this?

**Comment by imadejski** [comment]
Empty makefile was deleted. Adding it was an accident on our part. No other changes requested.

**Review by philipchenaux — APPROVED** [review]
Looks good to merge!

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent job on this PR!

**Pull request merged**
