### PR TITLE
sound: added documentation for the text to speech feature

### LINKED ISSUE #1577: sound: create documentation for text-to-speech
In this issue, we will create documentation for the text-to-speech feature in the sandbox module. We will create a README file that explains how to implement and use this feature. Hopefully, when the pull request is merged, other teams will be able to understand this feature and use it in their implementations.

Assignees: Rhea, Victor, Jake

### PR DESCRIPTION
**Pull request by sangerr**
In this pull request, we created documentation for the text-to-speech feature in the sandbox module. We added to the README file that explains what source used to develop this feature. The documentation we wrote also details how to compile and run the example file for text to speech. We hope that our description will help other teams to understand how to use the text to speech feature.

Assignees: Jake, Rhea, Victor

### CODE REVIEW

**Review by JaStarbuck — APPROVED** [review]
Looks good to me! Could be extra, but an extra comment telling the line number in which the text to speech can be changed could help others parse through the code and increase understandability.

**Review by ecoble — APPROVED** [review]
Looks good to me!

**Comment by jwschroeder21** [comment]
Closing statement:

We wrote documentation for the text-to-speech feature in the sandbox module. By adding to the README file that explains our modules, we detailed how to compile and run the example file for text to speech and cited our sources. Jason mentioned some changes about telling the line number in which the text to speech can be changed which could help others parse through the code and increase understandability. We made the changes and got the code merged !

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job writing thorough documentation! Please note that this PR was actually accidentally closed before it was merged, and as a result is just now being merged. Please be careful with closing PRs prematurely.

**Pull request merged**
