### PR TITLE
Sound: Wrote tests for sound.c functions

### LINKED ISSUE #1600: sound: Write tests for sound.c functions
In this issue, we need to write tests for `sound.c` functions, which include `load_wav`, `sound_free`, and `play_sound`. These tests will allow us to make sure that all the functions are working properly, so that we can make a successful demo.

Assignees: Rhea, Victor, Jake

### PR DESCRIPTION
**Pull request by sangerr**
In this pull request, we wrote tests for sound.c functions. In order to write the tests, we had to complete another issue where we created sound_init and sound_new functions. After that, we wrote tests for the load, new, init, play, and free functions, creating two tests per function (one for each sound type). 

Assignees: Rhea, Victor, Jake

### CODE REVIEW

**Comment by sangerr** [comment]
The tests keep having errors when compiling that relates to the CMake. Going to work on debugging this.

**Comment by jiaoboxuan** [comment]
Update: We have to make a hard trade-off here. We wrote 8 tests, 6 of which fail, 4 of the 6 due to segmentation fault, and the rest 2 due to function `load_wav` not working for some reason. The cause of the failure is very multifactorial, and so we won't have time to go into them. Therefore, I deleted all but 2 passing tests so that at least the code compiles. With this, I am also going to create a backlog issue for future teams interested in trying to debug this.

**Review by JaStarbuck — APPROVED** [review]
Looks good! I don't see anything wrong.

**Review by ecoble — CHANGES_REQUESTED** [review]
are these sounds the same ones you have added in another part of the code? if so, instead of duplicating the files, please just reference the file path of where they already exist.

**Comment by sangerr** [comment]
> are these sounds the same ones you have added in another part of the code? if so, instead of duplicating the files, please just reference the file path of where they already exist.

This branch was merged with the sound_init and sound_new PR for some reason, but the tests and code written in this branch are independent of that PR and this was submitted prior to the PR for that branch.

**Comment by jiaoboxuan** [comment]
> are these sounds the same ones you have added in another part of the code? if so, instead of duplicating the files, please just reference the file path of where they already exist.

I see what you mean -- yes. I'll make a quick change.

**Comment by jiaoboxuan** [comment]
Updated.

**Review by ecoble — APPROVED** [review]

**Comment by sangerr** [comment]
Closing Statement: In this PR, we created tests for the sound_new function. We initially implemented 8 tests for all of the functions in the sound.c file, but ultimately could only include the two sound_new tests because of compiler issues. Future teams should refer to the ["added sound_new, sound_init, sound_free, and play_sound tests" ](https://github.com/uchicago-cs/chiventure/pull/1652/commits/3e3563763352d0fb099e04b9c4969d10479f1ef7) commit to see the other potential tests and then work through debugging them. These tests are critical to making sure that our core sound.c functions are working, especially sound_new.

**Comment by sangerr** [comment]
Closing Summary: In this PR we wrote tests for the functions in sound.c. We initially wrote tests for the load, new, init, play, and free functions. However, we encountered challenges when trying to compile and run these tests. As such, we ended up only being able to keep 2/8 of the tests we wrote, which were the tests for sound_new. We would encourage future teams to combat the issue of compiling the other tests, as the testing of the core sound.c functions is critical.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job writing tests and being flexible with the issue. Hopefully future teams can get the rest of the tests working!

**Pull request merged**
