### PR TITLE
Battles/default objects

### PR DESCRIPTION
**Pull request by lczielinski**
We created a new battle src file, battle_default_objects.c, which has three functions for returning a default item, stat, and move. The default stat is more random, by choosing random numbers within a reasonable range for each field. There are 10 default items and moves each, which currently have very simple methods of determining fields (basically, the 10 items/moves increase in overall power). This could be tweaked in the future, but we think it is sufficient for the current purpose of being used in example battles. We also included a header file and a test file (with 2 new tests that pass). #876

### CODE REVIEW

**Review by Elsa-Athiley — APPROVED** [review]
Looks Awesome!

**Review by firatciftci — APPROVED** [review]
Great job! Everything looks good to go.

**Comment by lczielinski** [comment]
The pull request containing our code, new files being battle_default_objects.c, battle_default_objects.h, and test_battle_default_objects.c, has been merged. To summarize, the src file contains functions that return a randomized/default item, stat, and move to be used in an example battle.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job!

**Pull request merged**
