### PR TITLE
sound: created documentation for the tts structs

### LINKED ISSUE #1650: Sound: add tts struct documentation
After we have created the TTS struct, we want to provide documentation explaining its functionality. We will edit the README.md in src/sound to provide this documentation. This documentation will give an overview, covers basic structure, shows how to do an example demo, and includes info on the current status and future changes

Assignees: Parker, Rhea, Jake

### PR DESCRIPTION
**Pull request by sangerr**
In this pull request, we created documentation of how the text to speech structs work in the README file in src/sound. This documentation is necessary to understand how to use the text to speech feature in chiventure. We also hope that this documentation will provide future teams with a basis of how to further develop text to speech.

Assignees: Parker, Rhea, Jake

### CODE REVIEW

**Review by JaStarbuck — APPROVED** [review]
Also looks good! Thanks for doing this, it's very helpful

**Comment by jwschroeder21** [comment]
Update: after changing around the makefile we finally got this to compile and go through in our PR.

**Review by ecoble — APPROVED** [review]

**Comment by sangerr** [comment]
Closing Summary: In this pull request, we created documentation of how the text to speech structs work in the README file in src/sound. We ran into some issues with building the file, but were able to fix that by editing our CMake. We hope that this will help future teams understand how to use the tts structs.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job on this helpful documentation and debugging CMake issues!

**Pull request merged**
