### PR TITLE
Making split screen show images rather than a rectangle.

### PR DESCRIPTION
**Pull request by eao10000**
@grkapoor17 and I worked inside of the ui/examples directory working on changing split screen example to utilize images rather than rectangles as a graphic. Utilizing function such as LoadImage DrawTecture, ect we were able to successfully draw an image. For the image to work it has to be png and images under 500 x 500 pixels. Then adding 2 more pictures in the sandbox/images directory that works allowing for there to be 3 photos total.

### CODE REVIEW

**Review by grkapoor17 — APPROVED** [review]

**Review by MaxineK36 — CHANGES_REQUESTED** [review]
One small thing: can you note in a comment in your code what the requirements are for the images (size + extension)? Otherwise, looks awesome!

**Review by MaxineK36 — APPROVED** [review]
Looks great!

**Review by grkapoor17 — COMMENTED** [review]
Looks good!

**Comment by eao10000** [comment]
The change from rectangles to images in split-screen has been implemented, we had to utilize more function from raylib to complete this. While doing this we found that the images has to be 500 X 500 pixels or a png to work, this information has been included in the code.

**Pull request merged**
