### PR TITLE
Adding together chest/gold, player class WDLs, and torch example to the demo

### LINKED ISSUE #1700: Add extra functionality and final changes to the demo
Issue to track progress on changes that expand on the addition of custom actions based on classes (wizard/warrior itinerary example), lua scripts (chest and gold example), and booleans (torch example) through other small additions involving similar concepts based on the current integrated examples. 

Tied to pull request #1690.

### PR DESCRIPTION
**Pull request by mxu24**
These changes expand on the addition of custom actions based on classes (wizard/warrior itinerary example), lua scripts (chest and gold example), and booleans (torch example) through other small additions involving similar concepts based on the current integrated examples.

### CODE REVIEW

**Review by RamarkoB — APPROVED** [review]
Looks Good To Go! I made most of these changes, but the demo is running and everything looks solid!

**Comment by tatmaca** [comment]
> Looks Good To Go! I made most of these changes, but the demo is running and everything looks solid!

I decided to also take a look and everything runs perfectly on my end---Great work!

**Review by ecoble — APPROVED** [review]

**Comment by RamarkoB** [comment]
We restructured the map of our demo to create a more cohesive narrative of what the Custom Scripts team has accomplished this year. The demo will dynamically load a wdl file depending on input, as well as other examples that will change depending on input.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job polishing up the demo!

**Pull request merged**
