### PR TITLE
Graphics GDL Pull Request #2

### PR DESCRIPTION
**Pull request by imadejski**
A large amount of new, init, and frees additional tests were created for the other structs in the read_gdl files. This includes files for test_graphics, test_inventory, and test_stats. The Makefile was also edited accordingly. This was accidentally added to the PR #1 previously (see pull request 1 for documentation).

### CODE REVIEW

**Review by dhirpalshah — APPROVED** [review]
2nd part of gdl. looks great!

**Review by dhirpalshah — APPROVED** [review]
2nd part of gdl. looks great!

**Review by philipchenaux — APPROVED** [review]
Good coverage of testing functions, well done!

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent job on this PR!

**Pull request merged**
