### PR TITLE
Custom actions/1291 teleportation as a custom action redo

### PR DESCRIPTION
**Pull request by jbrouwer5**
We implemented TELEPORTATION as a custom action. A developer can now create a custom action that moves a player to a specified destination room. This involved creating a parameter struct that the action_new family of functions takes. This allows for more types of parameters rather than just attributes. We also implemented the applicable tests in the tests directory.

Pull Request #1373 has the same content, but was accidentally from a forked repo and needed to be merged first.

### CODE REVIEW

**Review by sabinecodes15 — APPROVED** [review]
No changes from previous review, so looks great!

**Review by ecoble — APPROVED** [review]
Approved from previous PR as well, nice work!

**Comment by jbrouwer5** [comment]
Relating to issue #1291, this pull request introduced TELEPORTATION as a new available custom action. The custom action takes a game and a destination room as parameters. The request has undergone both student and TA reviews. @sabinecodes15 gave very specific feedback, mostly relating to style and comments, which has been updated. After the changes from the review, this request was merged with no issues.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job implementing a new action, and working around merge issues!

**Pull request merged**
