### PR TITLE
Checkpointing/dev to proto branch

### PR DESCRIPTION
**Pull request by jonahdf**
Merging so I can work with updated structs

### CODE REVIEW

**Comment by mpcsh** [comment]
@jonahdf FYI, this doesn't need to be done via a PR. Check the updated developer guidelines.

**Comment by jonahdf** [comment]
@mpcsh Okay, thanks for letting me know.

**Comment by jonahdf** [comment]
@mpcsh I checked the developer guidelines and it only seems to mention branches for new features, not updating a previous branch. What would've been the correct way to do this?

**Comment by borjasotomayor** [comment]
@jonahdf: We actually posted about this on Slack:

> @channel: We have just approved the first PR into `master`, which means you can now update your `dev` branches with the latest code from `master` (this is something you will end up doing fairly frequently). To merge changes from `master`, one person in your team needs to do the following:
> 
> ```
> git checkout TEAM/dev
> git merge master
> # If necessary, resolve any merge conflicts
> git push
> ```
> 
> The rest of the team members should make sure to `git pull` to ensure they're working with the latest version of `dev`
> 
> To update a feature branch with the code that was merged into `dev` run the following:
> 
> ```
> git checkout TEAM/feature-branch
> git merge dev
> # If necessary, resolve any merge conflicts
> git push
> ```
> 
> (you should avoid merging from `master` directly into a feature branch; merging from `dev` ensures you incorporate any merge conflict resolutions when `master` was merged into `dev`)

It hasn't made its way into the Developer Guidelines, but will do so next time we update them.

**Pull request merged**
