### PR TITLE
Merge Ui/refactor structs to Ui/dev

### PR DESCRIPTION
**Pull request by omorkved**
See discussion in #131 for explanation of the changes I made. I also updated the makefile to include game-state headers--this code compiles, creates the ui.a library, and the coord_example executable runs correctly (with the text file generating containing all of the correct print statements). The only thing is in compiletime I get a warning that one of the game-state header files redefines SUCCESS/FAILURE, which are already definted in common.h. I did not want to change game-state's work, so I left as-is.

### CODE REVIEW

**Comment by omorkved** [comment]
There were some conflicts with map.h in dev but I fixed them (conflicts arose because I had deleted the dummy coord and room structs in map.h on my feature branch, and Sam had updated the map struct in the meanwhile)

**Comment by sebvil** [comment]
@omorkved this code does not compile. map.c is using the old room structs and is also missing the coordinate header, and therefore the build fails. Run make in both the UI directory and the root directory to make sure everything is compiling correctly.

**Comment by omorkved** [comment]
> @omorkved this code does not compile. map.c is using the old room structs and is also missing the coordinate header, and therefore the build fails. Run make in both the UI directory and the root directory to make sure everything is compiling correctly.

Mmm I see, I only ran it in the UI directory--will do.

**Comment by omorkved** [comment]
comments on map.c: I am also working on the map-from-coords branch with Sam, but I made clear comments so that when we have merge conflicts in Dev, it should be obvious which version to keep. The main problem was that the map.c code was using fields we had assumed room_t would have in our dummy struct. A lot of that info is now stored in the hashmap, which is what the map-from-coords branch is focused on integrating with. 

@sebvil

**Pull request merged**
