### PR TITLE
Skilltrees/demo bugfixes

### PR DESCRIPTION
**Pull request by rohangupta2806**
For some unknown reason, after our demo was merged with dev, it stopped working.  The code changes to cause it to start working again are fairly minor.  However, we only caught this issue after the code freeze.  This PR contains all the changes that we had to make.

### CODE REVIEW

**Review by tgao564 — APPROVED** [review]
Pretty simple changes, looks good to me! Thank you Rohan for working so hard on this!

**Review by firatciftci — APPROVED** [review]
Everything looks good to me.

**Review by borjasotomayor — APPROVED** [review]
LGTM! :shipit:

**Review by firatciftci — APPROVED** [review]
Looks good!

**Pull request merged**
