### PR TITLE
Playerclass/wdl loading: Load classes in from WDL files.

### PR DESCRIPTION
**Pull request by jackcasey067**
This pull request is associated with Issue #1079.  The goal was to be able to load classes from WDL files.  Most of the work is done; I am holding off on loading effects and skills (see the issue for more discussion on why).

This branch (`playerclass/WDL-loading`) has the changes from `playerclass/hashtable`, since the hashtable is where all a game's classes are stored.  Those changes are not yet merged into `dev`, which is the subject of PR #1061 (This accounts for about half of the changes in this PR).  If you are reviewing this PR, I recommend skimming over the previous one to see which changes are part of this one.

In broad strokes, changes include:
- A new module in WDL: `load_class`, which is responsible for loading all of the classes into memory.
    - It loads fully defined classes, partial classes, prefab classes, and partially overwritten prefab classes.
- Some code in the `validate` module that type checks and validates class objects before they are converted to `class_t`s.
- A small change to WDL's CMakeLists file.  Undoing it causes an insane linking error.
- Updates to the `class_prefabs` module, so that it takes a game_state_t instead of a chiventure_ctx_t (and cleaning it up a little).  
- `tests/wdl/examples/wdl/classes.wdl`, a WDL file that has classes (as well as a playable game copied from connect-rooms.wdl)
    - This is used in testing my new code.
- Tests, in `test_class.c`.

### CODE REVIEW

**Review by borjasotomayor — APPROVED** [review]
The changes that impact WDL look good to me!

**Review by firatciftci — APPROVED** [review]
Everything looks good to me, amazing work overall!

**Comment by jackcasey067** [comment]
Closing Statement:
This branch was merged into `dev`.  We can now (partially) load classes into memory from WDL.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work!

**Pull request merged**
