### PR TITLE
Emergency fix for name command

### PR DESCRIPTION
**Pull request by Gestalt-R**
The string I needed was freed for no particular reason. It should still be in use.

### CODE REVIEW

**Comment by Gestalt-R** [comment]
@mpcsh

**Comment by mpcsh** [comment]
Oops, that shouldn't have been an approval, my bad

**Comment by Gestalt-R** [comment]
It gets freed with the rest of the stuff in the hashtable.

**Comment by mpcsh** [comment]
Oh, then that should be an approval :thumbsup:

**Pull request merged**
