### PR TITLE
Clarified the example battle README

### PR DESCRIPTION
**Pull request by adinilfeld**
Clarified the README in ``/src/battle/examples/``, which previously contained vague and arguably incorrect instructions for running the example battle. Also updated the README to account for the fact that `battle_flow_example` is not currently functional.

(see issue #892)

### CODE REVIEW

**Review by lczielinski — APPROVED** [review]

**Review by Elsa-Athiley — APPROVED** [review]
The directions are way clearer, nice job!

**Review by jintae412 — APPROVED** [review]
Much clearer comments, and it's nice to know that the battle_flow is not currently functional.

**Review by sonnykaiyuenlee — APPROVED** [review]
Much clearer instructions than before. good job!

**Review by firatciftci — APPROVED** [review]
Looks good to me!

**Comment by adinilfeld** [comment]
@firatciftci Looks like the build check was cancelled -- does that mean my code caused an error? Or did something else go wrong?

**Comment by firatciftci** [comment]
I think it got stuck due to heavy load in Travis CI's servers and got canceled; I have run the tests again and everything looks good!

**Comment by adinilfeld** [comment]
Awesome, thanks! To summarize this merge: The README in `src/battle/examples` now gives clearer instructions for which commands to use to compile and run the example file. It also accounts for the fact that `battle_flow_example` is not currently functional.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job!

**Pull request merged**
