### PR TITLE
Tests for Parser Module

### PR DESCRIPTION
**Pull request by ecoble**
Created seven tests for the parser module, including:

- A test for empty input, expected return value: NULL
- A test for 1 word input, expected return value: Array of 4 words, first word being input value last 3 words being NULL
- A test for 2 word input, expected return value: Array of 4 words, first 2 words being words from input, last 2 words being NULL
- A test for 3 word input, expected return value: Array of 4 words, first 3 words being words from input, last word being NULL
- A test for 4 word input, expected return value: Array of 4 words, all words being words from input
- A test for 5 word input, expected return value: NULL
- A test for 3 word input with a lot of spaces between each word, expected return value: Same as test for normal 3 word input.

As part of the test for the empty string, the parser was updated with a catch at the beginning that returns NULL if given no input. This also sets up the basic structure for future tests, including a test folder, a main.c file, and a Makefile

Note: This will have some merge conflicts because an unfinished versions of the tests were pushed to the cli/dev branch, but they can be resolved quickly.

### CODE REVIEW

**Comment by Gestalt-R** [comment]
It looks workable, I can't see any issues if it compiles.

**Comment by Gestalt-R** [comment]
I also don't know what other tests to add, so I would just recommend tagging the issue number

**Comment by ecoble** [comment]
Issue #231

**Comment by ecoble** [comment]
CLOSING STATEMENT: The dev branch now includes tests for the parser module, including testing no input, tests for 1,2,3 and 4 word input, tests for other invalid input (more than 4 words), and a test for input with excessive spaces. This also included adding a catch for no input to the parser.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!

**Pull request merged**
