### PR TITLE
Added npc documentation to doc/

### LINKED ISSUE #894: Update Existing NPC Documentation
Assignee: Andrew, Matias, Dylan, Peter, James 
Team: npc-2

Review and update existing NPC documentation found on the npc/documentation branch. Update src/npc/README.md and create a markdown documentation file to add to the docs directory.

### PR DESCRIPTION
**Pull request by andrewg23**
The NPC module is a big feature in chiventure so it is important to have documentation explaining how the module works and how a game developer using chiventure would interact with it. This pull request adds npc.md as documentation which documents the existing code and supported functions. This resolves #894.

### CODE REVIEW

**Review by MaDDylan — APPROVED** [review]
Everything looks good!

**Review by lilyehsani — APPROVED** [review]
Well done! Everything looks good. Merging now so that it can be updated in future PRs.

**Comment by andrewg23** [comment]
This PR added the `docs/npc.md `file containing documentation on the NPC module including a list of all the files associated with the NPC module along with short descriptions of each file. It also updates the `docs/README.md` file to reflect this change. The approval of this PR also allows for the `npc/documentation` branch to be deleted.

NPC documentation was originally only found in s`rc/npc/README.md`, but It is now more intuitive to have the NPC documentation in the docs directory.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and closing of this PR are very straightforward.

**Pull request merged**
