### PR TITLE
WDL- Adding Tests for Inventory Conditions

### LINKED ISSUE #1516: Create Tests for Item Inventory Conditions
Issue #236 allows game developers to specify items that players must have in their inventory to perform certain actions. This functionality needs tests to ensure that inventory conditions are properly created. The current issue will be closed when these tests are implemented

### PR DESCRIPTION
**Pull request by sabinecodes15**
Issue #786 created a new mechanism to specify inventory conditions in a WDL. This PR implements a few tests for this new functionality in the file `test_conditions.c` under tests/wdl/, which tests the game specified in the file `inventory-cond.wdl`. Each test is given an item and one of the item's actions whose conditions are to be evaluated. The helper function `conditions_check()` verifies that an action with conditions specified in the WDL has those same conditions properly allocated in the associated game action, and an action without conditions specified does not have any allocated when the game is created.

While writing these tests, we also realized there were some redundancies in the way that test documents are loaded into objects. We added `test_wdl.c` and moved the implementation of `__get_doc_obj()` into this file so that this function would be inherited by each test file, rather than copied over. We also moved some include statements that were common to all the test files into the header file `test_wdl.h`.

### CODE REVIEW

**Review by wellingtj — COMMENTED** [review]
I'm reviewing from the player classes group, so I will try to let someone from the WDL group be the approving reviewer since they can give a more comprehensive review of the code, but I think all in all from what I can understand of the WDL code this is mostly fine. One potential suggestion (that might not be needed if I'm misunderstanding) is that all of the classes you chose have since been redone. Monk and Rogue now are fully defined, knight was removed, and warrior is completed I believe. That being said, if this works differently in the WDL as opposed to our class module this makes sense. Additionally if yall somehow need me to be the person to approve this instead of someone from the WDL team let me know and I can.

**Review by KendrickXie — APPROVED** [review]
Looks good to me. As you said in your comment, it looks like you got rid of a lot of redundancies. Good work!

**Comment by ecoble** [comment]
> I'm reviewing from the player classes group, so I will try to let someone from the WDL group be the approving reviewer since they can give a more comprehensive review of the code, but I think all in all from what I can understand of the WDL code this is mostly fine. One potential suggestion (that might not be needed if I'm misunderstanding) is that all of the classes you chose have since been redone. Monk and Rogue now are fully defined, knight was removed, and warrior is completed I believe. That being said, if this works differently in the WDL as opposed to our class module this makes sense. Additionally if yall somehow need me to be the person to approve this instead of someone from the WDL team let me know and I can.

This year there is no WDL group, so please go ahead and review this!

**Review by wellingtj — APPROVED** [review]

**Review by jakeziqiwei — APPROVED** [review]
looks good

**Review by ecoble — APPROVED** [review]
Looks great!

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job writing tests and cleaning up existing code, especially on a lot of cross team modules!

**Pull request merged**
