### PR TITLE
Action management demo

### PR DESCRIPTION
**Pull request by ericyc16**
Resolves issue #667 

To demonstrate the features that the action management team has been working on all quarter, I have created a demo game in the `src/action_management/examples` directory. Currently, this game demonstrates the following features:
- End conditions
- Inventory conditions
- Item stacking
- Action synonyms
Currently, conditional connections between rooms has not been merged with dev. If this gets done in time, I will update the demo game and create a separate PR to include this feature as well

### CODE REVIEW

**Comment by victoriavillalba** [comment]
There are some problems when I run it
Screen Shot 2020-06-08 at 2 09 15 PM

**Comment by ericyc16** [comment]
> There are some problems when I run it
> Screen Shot 2020-06-08 at 2 09 15 PM

I think that looks like a problem from another team's end that somehow got into dev

**Comment by ericyc16** [comment]
Demo game has been pulled into dev! There was a problem that seemed to pop up where inventory conditions were not being properly created and action synonyms were not working, but that problem seems to have fixed itself. I will be closing the related issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great job! Thanks for listing out all the changes and linking all relevant issues.

**Pull request merged**
