### PR TITLE
Implement talk operation for conversations

### LINKED ISSUE #1059: Implement talk to NPC operation
For the implementation of NPC actions, we've determined that actions that implement game logic at a higher level than just changing an attribute or transferring possession of an item should have there own operation always added to chiventure's lookup table. This includes the talk action, which needs to change chiventure to conversation mode and start the npc's conversation. We will implement that operation.
Assignees: Peter, Dylan
team:npc2

### PR DESCRIPTION
**Pull request by pkasner**
Closes #1059 
In order to initiate conversation mode, this branch implements a talk_operation() function, and adds a corresponding entry to chiventure's lookup table as a built in command.
Here are the changes made:
- A talk operation function was implemented, following the operation typedef defined by the CLI.
- The talk operation parses the user's to determine which npc is spoken too, or if the command is not formatted correctly. The switches the game to conversation mode accordingly.
- Implemented a set_game_mode function to factor some more intricate calls to game_mode_init
- Added unit tests for get_npc and add_npc_to_game

Additional Notes:
- Some code, previously commented out, relies on npc room integration from #1082, This PR should be merged after that one to allow for that code to be changed.
- The talk_operation now supports room integration, as the room integration branch has been merged.
- In order to store npcs in multiple hash tables (all_npcs in the game struct, and npc_list in npcs_in_room struct), it was necessary to add a second hash handle, hh_room, to the npc struct. Functions that interact with the second hash table have been updated accordingly.

### CODE REVIEW

**Comment by jeyeong** [comment]
This looks good to me! As you've mentioned, we'll probably want to merge it after npc/room-integration is merged. But I'll approve it for now

**Review by jeyeong — APPROVED** [review]

**Comment by pkasner** [comment]
Room integration has been merged, so this branch has been updated accordingly. The talk_operation now ensures that the npc is in the current room in order to talk to them.

**Review by lilyehsani — APPROVED** [review]
Looks great!

**Comment by pkasner** [comment]
Now that the talk operation has been implemented, basic npc dialogue is now fully supported in chiventure. The next steps include making sure conversations, along with NPCs, can be loaded into the game through the object store, and the completion of more advanced dialogue features such as conditional dialogue and dialogue based actions. All these steps are currently in the process of being merged into chiventure and should be wrapped up soon.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and closing of this PR are very thorough.

**Pull request merged**
