### PR TITLE
Renamed game_t to battle_game_t

### PR DESCRIPTION
**Pull request by Elsa-Athiley**
Implemented the final renaming of the game_t struct to battle_game_t to resolve the problem of duplicates between battle code and game state code.

### CODE REVIEW

**Review by sonnykaiyuenlee — APPROVED** [review]
good work getting this quick and helpful task done to keep the ball rolling

**Review by firatciftci — APPROVED** [review]
Everything looks good to me!

**Comment by Elsa-Athiley** [comment]
Closing statement: Changes included renaming all instances of game_t to battle_game_t also includes some naming changes of player_t to battle_player_t that were missed in a previous PR

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good job! I only have one thing to comment on:
- The summary for this PR is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples).

**Pull request merged**
