### PR TITLE
Updating the in-repository NPC.md documentation and Rearranging functions in npc.h

### LINKED ISSUE #1197: Review State of NPC Movement and Update Existing Documentation/Create Wishlist

### PR DESCRIPTION
**Pull request by bvvill**
Upon inspection of npc.md, in the docs folder, it was apparent that the file hadn't been updated in quite some time, and did not include documentation of the npc_move or npc_battle modules. In the npc/move/update-documentation branch, I have added the general features of both of those modules as well as a possible next step for the npc_move module. In the npc/move/update-documentation branch, I have also implemented a get_npc_mov function, as the npc_mov_t member of the npc struct was the only one that didn't have an implementation of a "get _____" function. I also slightly rearranged a few of the functions in the npc.h/.c modules in order to group those functions with those similar to them.

### CODE REVIEW

**Review by srydbergcox — APPROVED** [review]
Nice work Will! I think that overall, your additions to the code base look good. I just have a couple notes about the documentation of what you did. You have a nice summary that helped me understand what you did, but I think your title could be slightly more descriptive. Also, you are missing status updates and a closing statement. Lily can correct me if I'm wrong but I think it would have been helpful just to have quick comments to track the progression of the issue and then a final update when you finished. Other than the updates though, great work!

**Comment by bvvill** [comment]
>Also, you are missing status updates and a closing statement. Lily can correct me if I'm wrong but I think it would have been helpful just to have quick comments to track the progression of the issue and then a final update when you finished. Other than the updates though, great work!

Yeah this is fair, I was definitely rushing so I could move on to sprint 2, and thank u !

**Review by lilyehsani — APPROVED** [review]
Looks good! Approved.

**Comment by bvvill** [comment]
> Upon inspection of npc.md, in the docs folder, it was apparent that the file hadn't been updated in quite some time, and did not include documentation of the npc_move or npc_battle modules. In the npc/move/update-documentation branch, I have added the general features of both of those modules as well as a possible next step for the npc_move module. In the npc/move/update-documentation branch, I have also implemented a get_npc_mov function, as the npc_mov_t member of the npc struct was the only one that didn't have an implementation of a "get _____" function. I also slightly rearranged a few of the functions in the npc.h/.c modules in order to group those functions with those similar to them.

this was my closing statement

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! The same statement really should not be the summary as well as closing. The statement you gave is a good summary, and the closing should react to any changes requested on the PR, or the lack thereof.

**Pull request merged**
