### PR TITLE
Move the multiclassing features into its own module

### PR DESCRIPTION
**Pull request by wellingtj**
Currently, the class.c file contains a lot of code on multi-classing. This includes functions like multiclass_shortdesc, multiclass_longdesc, multiclass, has_component_class. It would therefore make sense to move the multiclassing features into their own module so that we can expand them. This pull request has taken care of that task as well as all of the necessary changes to the cmake files and header files

### CODE REVIEW

**Comment by wellingtj** [comment]
I have refactored multiclassing code into its own module

**Comment by wellingtj** [comment]
This is for issue #1287

**Review by Vincent-Zhang4135 — APPROVED** [review]
Jake, you did a great job refactoring player class into a class and multi class functional modules. abstracting away these into these two files will come in handy to future developers that need to use these modules, as they will have an easier time digging into the code base to see what functionalities we support. 

I appreciate your carefulness in also making sure to update the CMakeList.txt to include this new header file when we link/compile our code. From what I see, your code passes the build, and so I would like to approve this and move this onto Lily for a final approval.

**Review by lilyehsani — APPROVED** [review]
Looks good to me! Approved.

**Comment by wellingtj** [comment]
All the multiclassing features previously in class.c are in their own module multiclassing.c. The functionality remains intact, the linking works, and the modlue is now completely refactored

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this PR!

**Pull request merged**
