### PR TITLE
changed naming of class_t fields in structs

### PR DESCRIPTION
**Pull request by Elsa-Athiley**
previously they were named class and this was causing a problem because use the playerclass team also chose class as the naming for their struct definition. 
See below:
`
typedef struct class {    
    // Name of the class    
    char* name;
    // A short description of the class    
    char* shortdesc;
    // A long description of the class    
char* longdesc;
 ...
} class_t;`

`
typedef struct player {     
char *player_id;    
class_t *class;    
stat_t *stats;    
move_t *moves;    
battle_item_t *items;
} player_t;`

note: the player_t struct has changed to battle_player_t implemented in another PR

### CODE REVIEW

**Review by lczielinski — APPROVED** [review]
Looks good to me

**Review by firatciftci — APPROVED** [review]
Everything looks good to me!

**Comment by Elsa-Athiley** [comment]
Closing statement, This code that was pushed included changes to struct definitions and function definitions that were the form `class_t class;` and accesses to that struct field such as `player->class`. These have been changed to` class_type,` and `c_type`. The problem was the player class used the same naming when defining the original class struct which was causing errors.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work!

**Pull request merged**
