### PR TITLE
Adding get description from item functions to game-state/dev

### PR DESCRIPTION
**Pull request by jessxia**
Added two functions, get_sdesc_item and get_ldesc_item into item.h and item.c. These functions return the short and long descriptions stored in an item (for issue #202). Also added two tests into test_items.c to test these functions.

### CODE REVIEW

**Comment by a-matai** [comment]
Can you add a test for if there is no ldesc / if taken from a null item? 

Code is fine, but I'd suggest a check incase a null item is fed in?

**Comment by jessxia** [comment]
NULL items now return NULL for both functions :))

**Comment by a-matai** [comment]
Yay!

**Comment by jessxia** [comment]
Get_sdesc_item and get_ldesc_item were added to our item module to return short and long descriptions of items, or NULL if NULL item. Tests were written and pass.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work! Though it's important that the reviewers approve explicitly on github.

**Pull request merged**
