### PR TITLE
Added effects and conditions to function do_item_action and its tests

### PR DESCRIPTION
**Pull request by SnowballAntrobus**
Changes:

- Added functionality to do_item_action so that now (using GS functions) it checks conditions and changes state (item attributes) according to effects. 
- Added tests to do_item_action_tests that check for correct functionality when dealing with conditions and effects.

This is the PR for issues #190 and #192.

### CODE REVIEW

**Comment by MTUC08** [comment]
> I approve the function + tests so long as they compile + pass!
> 
> I am slightly concerned about the random UI files altered however, so if you could figure out what's causing that it would be great

Might be due to the new ui foxes in master? Try merging with master and see if they go away.

**Comment by SnowballAntrobus** [comment]
Done! Pretty sure it fixed it.

**Comment by SnowballAntrobus** [comment]
Closing Statement:
We have now finished writing the full functionality of the do_item_action function and it's respective tests. We added implementation and tests for effects and conditions. We will proceed by checking for compatibility as the GS functions make it to master.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!

**Pull request merged**
