### PR TITLE
Implementing surrender level for battles in the battles module to support NPC module changes

### LINKED ISSUE #1448: Implement surrender level for battles in the battles module to support the NPC module changes.
The goal of this pull request is to implement surrender level into stat_t for the NPC Module to accommodate this [issue](https://github.com/uchicago-cs/chiventure/pull/1400). This would actually allow battles to end when the NPC's hp has gone below the surrender level. We would also like to return a new identifier for when a NPC surrenders as opposed to being defeated.

### PR DESCRIPTION
**Pull request by nmkhan100**
We are creating this pull request in order to allow NPCs to surrender once they reach a certain HP level. We have added a surrender_level field into the stat_t struct and changed the battle_status_t enum to include BATTLE_ENEMY_SURRENDER. We have changed two functions, battle_flow_move() which now incorporates surrender level, and print_battle_winner() which prints a new statement for when the enemy surrenders. 

Here is a link to the changes we are trying to support with this PR : (https://github.com/uchicago-cs/chiventure/pull/1400)

### CODE REVIEW

**Review by corian-jal — APPROVED** [review]
Everything looks good here to me! Most of it is just small insertions and the new tests seem reasonable, so I think it's good to merge fairly as-is.

**Review by emilybae1705 — APPROVED** [review]
Looks great! I approve of this PR as `surrender_level` has been implemented in all the necessary places and I don't see any issues with it. Now that `surrender_level` has been added, I can go ahead and uncomment the code in `npc/examples/battle_move_example_2021.c`. One clarifying question, though: will players be able to surrender their own games or is surrendering only what their opponents can do?

**Review by lilyehsani — APPROVED** [review]
LGTM! Approved.

**Comment by nmkhan100** [comment]
We have modified the stat_t struct by introducing a new field, the surrender_level field, and we have changed the battle_status enum so it now includes BATTLE_ENEMY_SURRENDER. Because of these changes, we also changed two functions, the battle_flow_move() function which now includes the surrender level, and the print_battle_winner() function which now prints a statement for when an opponent surrenders. These are the the functions we have modified, though there may be more that we must change in the future. And to make testing easier, we have added new tests based on our changes.

Here is a link to the changes we're supporting: (https://github.com/uchicago-cs/chiventure/pull/1400)

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this PR!

**Pull request merged**
