### PR TITLE
PR for default battle items/consumables and stats

### PR DESCRIPTION
**Pull request by sonnykaiyuenlee**
We have integrated our functions for default items and stats into the battle example. Waiting to integrate move until we have more information from the playerclass team. For items, we created an additional function to produce default consumable items (items that update stats of a player) to better integrate with the work done with other members of our group. We will figure out integrating weapons items later.

### CODE REVIEW

**Review by Elsa-Athiley — APPROVED** [review]
This looks great! good job

**Review by jintae412 — APPROVED** [review]
As far as I can tell there's nothing wrong with the code you've written, or the design that you wrote it with. I see no reason not to approve of this.

**Review by firatciftci — APPROVED** [review]
Everything looks good to me as well!

**Comment by lczielinski** [comment]
To summarize this pull request, we added a function in battle_default_objects that would return a random consumable that could then be used in battle. We distinguished between consumables and weapons, and will further work on implementing weapon use into battles. We then used the random consumable function and stat function in the example battle code, so each time the example battle is run, the player and enemy have random stats and the player has a random consumable they can use. Finally, we updated the readme and tests to accommodate the new functions.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job!

**Pull request merged**
