### PR TITLE
Checkpointing/make

### PR DESCRIPTION
**Pull request by jarvislam1999**
Fixed Makefile to compile for chiventure. Only solution we could have thought of. Typing make in chiventure compiles now. Yay?

### CODE REVIEW

**Comment by jonahdf** [comment]
I resolved the merge conflicts with Ryan

**Comment by mpcsh** [comment]
@jarvislam1999 can you please back out the style changes to CLI's code? We should avoid touching code that isn't ours, even if it does need a style update.

**Comment by Gestalt-R** [comment]
Yeah, our code uses the allman style. Please don't change it without asking.

**Comment by mpcsh** [comment]
@Gestalt-R the issue at hand was not the choice of Allman style but rather things like `while(condition)` instead of `while (condition)` (the former not being acceptable regardless of brace style). Regardless, the point was to not generate a diff unless necessary.

**Comment by Gestalt-R** [comment]
Regardless, the style change was also incorporated into the request.

**Comment by jonahdf** [comment]
@mpcsh I reverted the style commit. Are we good to merge now?

**Comment by mpcsh** [comment]
@jonahdf it looks like the `master` merge you did here picked up commits that `dev` doesn't have - can you merge `master` into `dev` again?

**Comment by mpcsh** [comment]
@jonahdf actually you'll have to merge `master` into both `dev` and this branch, `master` just saw yet another merge

**Comment by jonahdf** [comment]
I tried merging master, it got quite complex, partially because of David's changes to dev and lots of merge conflicts that I had to resolve in both dev and make. I decided it would be simpler to just make the changes in dev, and include that in the #311 (and close this PR). Everything now compiles in dev!

**Pull request closed without merging**
