### PR TITLE
adding changes to the README.md

### LINKED ISSUE #1436: sound: documentation for other teams to use sound in their module
In this issue we aim to create documentation for other teams to use in their sound module. We will update the README document for this purpose. We are planning on collaborating with the RPG battle team on sound integration (for reference).

assignees: Jake, Rhea, Parker

### PR DESCRIPTION
**Pull request by jwschroeder21**
in this pull request, we will add changes to the readme to provide documentation for other teams to use in their sound module. The RPG battle team specifically requested this information. 

assignees: Jake, rhea, Parker

### CODE REVIEW

**Review by jiaoboxuan — COMMENTED** [review]
Line 15: "Declare `sound_t` variable whenever a sound is needed. Preferably, if a sound is associated with an action, then the `sound_t` variable should be declared and freed within the function". Also, write something about the two types of arrays (`Mix_Chunk` and `Mix_Music`), the former for sound effects (multiple sounds could be played at the same time), and the latter for background music (only one sound could be played at a time). I wrote the same thing in the `README.md` in `sandbox` folder, but might as well copy them here.

**Comment by jwschroeder21** [comment]
Thank you Victor! I made the changes and pushed again. Also updated the wiki.

**Comment by jwschroeder21** [comment]
closing statement: 

in this pull request, we have added changes to the README that provide documentation for other teams to use in their sound module. we specifically added documentation on mp3 files, wav files, sound_t declaration, and Mix_Chunk + Mix_Music specification. we will meet with the reg battle team Wednesday at 5pm to further discuss this in person, but hopefully the documentation should help!

**Review by ecoble — APPROVED** [review]
Looks good, nice documentation!

**Review by jiaoboxuan — APPROVED** [review]

**Comment by jwschroeder21** [comment]
Summary:

in this pull request, we have added changes to the README that provide documentation for other teams to use in their sound module. we specifically added documentation on mp3 files, wav files, sound_t declaration, and Mix_Chunk + Mix_Music specification. we will meet with the reg battle team Wednesday at 5pm to further discuss this in person, but hopefully the documentation should help!

**Pull request closed without merging**
